package Interfaz;
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setLocationRelativeTo (null);
        setResizable (false);
        setTitle ("Administración");
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 567));
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 0));
        jLabel11.setText("En Espera");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(410, 80, 140, 21);

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 0));
        jLabel10.setText("No perecederos");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 310, 190, 21);

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 150, 110, 30);

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 0));
        jLabel14.setText("Modificar cantidad de ventanillas");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 0, 390, 21);

        jLabel20.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 102, 0));
        jLabel20.setText("Clientes por");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 330, 150, 29);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Siguiente por");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 380, 150, 21);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel6AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 290, 100, 30);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Cola de prioridad");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 250, 210, 24);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Promedio de espera");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 240, 220, 21);

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 0));
        jLabel12.setText("Cantidad de");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 280, 140, 24);

        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 102, 0));
        jLabel19.setText("Clientes atendidos");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(400, 280, 230, 29);

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 0));
        jLabel7.setText("Espera");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 450, 90, 21);

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 380, 160, 30);

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 102, 0));
        jLabel21.setText("Atender");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(10, 400, 140, 21);

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel22AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(150, 70, 70, 30);

        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 102, 0));
        jLabel18.setText(" en seguridad ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(400, 40, 170, 24);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Fichas en");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 430, 110, 21);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("ventanillas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 300, 130, 21);

        jLabel23.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 102, 0));
        jLabel23.setText("ventanilla");
        jLabel23.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel23AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 350, 130, 21);

        jComboBox1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jComboBox1.setMaximumRowCount(14);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 430, 150, 27);

        jComboBox2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jComboBox2.setMaximumRowCount(14);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(170, 340, 150, 27);

        jLabel29.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 102, 0));
        jLabel29.setText("Siguiente por");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(230, 100, 150, 21);

        jComboBox3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jComboBox3.setMaximumRowCount(14);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(0, 70, 150, 27);

        jLabel27.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 102, 0));
        jLabel27.setText("Clientes por");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 30, 150, 29);

        jLabel26.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel26AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel26);
        jLabel26.setBounds(240, 70, 100, 30);

        jComboBox4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jComboBox4.setMaximumRowCount(14);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(0, 150, 150, 27);

        jLabel24.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 102, 0));
        jLabel24.setText("Cantidad de");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(240, 30, 140, 24);

        jLabel28.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 102, 0));
        jLabel28.setText("ventanilla");
        jLabel28.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel28AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 50, 130, 21);

        jLabel30.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 102, 0));
        jLabel30.setText("Atender");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(240, 120, 140, 21);

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 0));
        jLabel13.setText("Árbol Heap");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 140, 24);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 190, 870, 10);

        jLabel25.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 102, 0));
        jLabel25.setText("ventanillas");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(240, 50, 130, 21);

        jLabel31.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel31);
        jLabel31.setBounds(220, 140, 160, 40);

        jLabel32.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 102, 0));
        jLabel32.setText("Fichas en");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 110, 110, 21);

        jLabel33.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 102, 0));
        jLabel33.setText("Espera");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 130, 90, 21);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(390, 0, 10, 540);

        jLabel34.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel34AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel34);
        jLabel34.setBounds(320, 90, 70, 30);

        jTextField1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(600, 80, 120, 25);

        jTextField2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(600, 40, 120, 25);

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("En Seguridad");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 260, 170, 21);

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(400, 330, 130, 30);

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 102, 0));
        jLabel17.setText("Fichas    P    NP    D    M    E     R");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(400, 480, 420, 21);

        jLabel35.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 102, 0));
        jLabel35.setText("En entregas");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(400, 220, 138, 21);

        jLabel36.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel36);
        jLabel36.setBounds(650, 200, 130, 30);

        jLabel38.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 102, 0));
        jLabel38.setText("Perecederos");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(640, 310, 147, 21);

        jLabel39.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 102, 0));
        jLabel39.setText("En Seguridad");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(580, 460, 150, 21);

        jLabel41.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel41);
        jLabel41.setBounds(650, 330, 130, 30);

        jLabel40.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel40);
        jLabel40.setBounds(650, 240, 130, 30);

        jLabel42.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel42AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel42);
        jLabel42.setBounds(320, 340, 70, 30);

        jLabel43.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel43);
        jLabel43.setBounds(730, 440, 70, 40);

        jLabel44.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 102, 0));
        jLabel44.setText("Clientes");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(580, 420, 110, 21);

        jComboBox6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(400, 420, 170, 24);

        jComboBox7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jComboBox7.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(400, 360, 170, 24);

        jComboBox8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jComboBox8.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(400, 360, 170, 24);

        jLabel45.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 102, 0));
        jLabel45.setText("atendidos");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(580, 440, 110, 21);

        jLabel46.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 102, 0));
        jLabel46.setText("En entregas");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(580, 400, 140, 21);

        jLabel47.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 102, 0));
        jLabel47.setText("Clientes");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(580, 360, 110, 21);

        jLabel48.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 102, 0));
        jLabel48.setText("Clientes");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(580, 360, 110, 21);

        jComboBox9.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jComboBox9.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(400, 360, 170, 24);

        jLabel49.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 102, 0));
        jLabel49.setText("En entregas");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(580, 400, 140, 21);

        jLabel50.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 102, 0));
        jLabel50.setText("atendidos");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(580, 380, 110, 21);

        jLabel51.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel51);
        jLabel51.setBounds(690, 360, 120, 40);

        jLabel37.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 102, 0));
        jLabel37.setText("Promedio de espera");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(400, 200, 220, 21);

        jLabel52.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel52);
        jLabel52.setBounds(670, 500, 40, 20);

        jLabel53.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel53);
        jLabel53.setBounds(530, 500, 40, 20);

        jLabel55.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel55);
        jLabel55.setBounds(630, 500, 40, 20);

        jLabel54.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel54);
        jLabel54.setBounds(710, 500, 40, 20);

        jLabel56.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel56);
        jLabel56.setBounds(490, 500, 40, 20);

        jLabel57.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel57);
        jLabel57.setBounds(580, 500, 40, 20);

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/progra_1.jpg"))); // NOI18N
        jLabel16.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel16AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, -110, 1320, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel16AncestorAdded

        ;
    }//GEN-LAST:event_jLabel16AncestorAdded

    private void jLabel6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel6AncestorAdded

    }//GEN-LAST:event_jLabel6AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel23AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel23AncestorAdded

    }//GEN-LAST:event_jLabel23AncestorAdded

    private void jLabel22AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel22AncestorAdded

    }//GEN-LAST:event_jLabel22AncestorAdded

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jLabel26AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel26AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26AncestorAdded

    private void jLabel28AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel28AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28AncestorAdded

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jLabel34AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel34AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34AncestorAdded

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel42AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel42AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42AncestorAdded

  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
